KALBE/Models/ErrorViewModel.cs
namespace KALBE.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

KALBE/Controllers/CustomerController.cs
using kalbe.datamodels;
using kalbe.viewmodels;
using kalbe.web.Services;
using Microsoft.AspNetCore.Mvc;

namespace kalbe.web.Controllers
{
	public class CustomerController : Controller
	{
		private CustomerService customerService;

        public CustomerController(CustomerService _cutomerService)
        {
			this.customerService = _cutomerService;
        }
		public async Task<IActionResult> Index(string sortOrder,
												string searchString,
												string currentFilter,
												int? pageNumber,
												int? pageSize)
		{
			ViewBag.CurrentSort = sortOrder;
			ViewBag.CurrentPageSize = pageSize;
			ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
			if (searchString != null)
			{
				pageNumber = 1;
			}
			else
			{
				searchString = currentFilter;
			}
			ViewBag.CurrentFilter = searchString;
			List<Customer> data = await customerService.GetAllData();

			if (!string.IsNullOrEmpty(searchString))
			{
				data = data.Where(a => a.TxtCustomerName.ToLower().Contains(searchString.ToLower())
					).ToList();
			}

			switch (sortOrder)
			{
				case "name_desc":
					data = data.OrderByDescending(a => a.TxtCustomerName).ToList();
					break;
				default:
					data = data.OrderBy(a => a.TxtCustomerName).ToList();
					break;
			}

			return View(PaginatedList<Customer>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));

		}

		public IActionResult Create()
		{
			Customer data = new Customer();
			return PartialView(data);
		}

		[HttpPost]
		public async Task<IActionResult> Create(Customer dataParam)
		{

			VMResponse respon = await customerService.Create(dataParam);
			if (respon.Success)
			{
				return Json(new { dataRespon = respon });
			}
			return View(dataParam);
		}
		public async Task<JsonResult> CheckNameIsExist(string CustomerName)
		{
			bool isExist = await customerService.CheckCustomerName(CustomerName);
			return Json(isExist);

		}

		public async Task<IActionResult> Detail(int id)
		{
			Customer data = await customerService.GetDataById(id);
			return PartialView(data);
		}

		public async Task<IActionResult> Delete(int id)
		{
			Customer data = await customerService.GetDataById(id);
			return PartialView(data);
		}

		public async Task<IActionResult> SureDelete(int id)
		{

			VMResponse respon = await customerService.Delete(id);

			if (respon.Success)
			{
				return RedirectToAction("Index");
			}
			else
				return RedirectToAction("Index", id);
		}

		public async Task<IActionResult> Edit(int id)
		{
			Customer data = await customerService.GetDataById(id);
			return PartialView(data);
		}

		[HttpPost]
		public async Task<IActionResult> Edit(Customer dataParam)
		{

			VMResponse respon = await customerService.Edit(dataParam);
			if (respon.Success)
			{
				return Json(new { dataRespon = respon });
			}
			return View(dataParam);
		}

	}
}

KALBE/Controllers/HomeController.cs
using System.Diagnostics;
using KALBE.Models;
using Microsoft.AspNetCore.Mvc;

namespace KALBE.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

KALBE/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using kalbe.datamodels;
using kalbe.viewmodels;
using kalbe.web.Services;

namespace kalbe.web.Controllers
{
    public class ProductController : Controller
    {
        private ProductService productService;

        public ProductController(ProductService _productService)
        {
            this.productService = _productService;
        }

        public async Task<IActionResult> Index(string sortOrder,
                                                string searchString,
                                                string currentFilter,
                                                int? pageNumber,
                                                int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            List<Produk> data = await productService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.TxtProductName.ToLower().Contains(searchString.ToLower())
                    ).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.TxtProductName).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.TxtProductName).ToList();
                    break;
            }

            return View(PaginatedList<Produk>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));

        }

		public IActionResult Create()
		{
			Produk data = new Produk();
			return PartialView(data);
		}

		[HttpPost]
		public async Task<IActionResult> Create(Produk dataParam)
		{
			
			VMResponse respon = await productService.Create(dataParam);
			if (respon.Success)
			{
				return Json(new { dataRespon = respon });
			}
			return View(dataParam);
		}

		public async Task<JsonResult> CheckNameIsExist(string ProductName)
		{
			bool isExist = await productService.CheckProdukByName(ProductName);
			return Json(isExist);

		}

		public async Task<IActionResult> Detail(int id)
		{
			Produk data = await productService.GetDataById(id);
			return PartialView(data);
		}

		public async Task<IActionResult> Delete(int id)
		{
			Produk data = await productService.GetDataById(id);
			return PartialView(data);
		}

		public async Task<IActionResult> SureDelete(int id)
		{

			VMResponse respon = await productService.Delete(id);

			if (respon.Success)
			{
				return RedirectToAction("Index");
			}
			else
				return RedirectToAction("Index", id);
		}

        public async Task<IActionResult> Edit(int id)
        {
            Produk data = await productService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Produk dataParam)
        {
         
            VMResponse respon = await productService.Edit(dataParam);
            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }
    }
}

KALBE/Views/Customer/Create.cshtml
@using kalbe.datamodels
@model Customer
@{

	ViewData["Title"] = "Create Customer";
}

<div class="card">
	<div class="card-body">
		<div class="card-title">@ViewData["Title"]</div>
		<form asp-action="Create" method="post" id="form_input">
			<div class="mb-4 row">
				<label for="TxtCustomerName" class="col-sm-4 col-form-label">Customer Name</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" id="TxtCustomerName" name="TxtCustomerName" value="@Model.TxtCustomerName">
					<span id="validateCustomerName" class="text-danger"></span>
				</div>
			</div>
			<div class="mb-4 row">
				<label for="TxtCustomerAddress" class="col-sm-4 col-form-label">Customer Address</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" id="TxtCustomerAddress" name="TxtCustomerAddress" value="@Model.TxtCustomerAddress">
				</div>
			</div>
			<div class="mb-4 row">
				<label for="BitGender" class="col-sm-4 col-form-label">Gender</label>
				<div class="col-sm-8">
					<select id="BitGender" name="BitGender" class="form-control">
						<option value="">-- Choose Gender --</option>
						<option value="true">Male</option>
						<option value="false">Female</option>
					</select>
				</div>
			</div>
			<div class="mb-4 row">
				<label for="DtmBirthDate" class="col-sm-4 col-form-label">Birth Date</label>
				<div class="col-sm-8">
					<input type="date" class="form-control" id="DtmBirthDate" name="DtmBirthDate" value="@Model.DtmBirthDate">
				</div>
			</div>

			<div class="modal-footer">
				<div class="col-sm-12">
					<a class="btn btn-outline-secondary btn-rounded" asp-controller="Customer" asp-action="Index">Back to List</a>
					<button type="submit" style="float:right" class="btn btn-primary btn-rounded">Submit</button>
				</div>
			</div>
		</form>

	</div>
</div>

<script>



	$("#form_input").validate({
		errorClass: "text-danger",
		rules: {
			TxtCustomerName: {
				required: true,
				minlength: 3,
			},
			TxtCustomerAddress: "required",
			BitGender: "required",
			DtmBirthDate: "required"
		},
		messages: {
			TxtProductName: {
				required: "Please fill name customer!",
				minlength: "The Name must consist of at least 3 character!",
			},
			TxtCustomerAddress: "Please fill name customer!",
			BitGender: "Choose your gender",
			DtmBirthDate: "Please fill your birth date"
		},
		submitHandler: function (form) {
			var dataForm = $(form).serialize();
			var CustomerName = $("#TxtCustomerName").val();

			$.ajax({
				url: "/Customer/CheckNameIsExist",
				//method: "GET"
				type: "GET",
				data: { CustomerName: CustomerName },
				dataType: "json",
				success: function (respon) {
					if (respon) {
						$("#validateCustomerName").text("Name Customer is already exist")
						return true
					}
					else {
						fungsiSubmit(dataForm)
					}
				}
			})
		}
	})

	function fungsiSubmit(dataParam) {
		$.ajax({
			url: "/Customer/Create",
			type: "POST",
			dataType: "json",
			data: dataParam,
			success: function (respon) {
				var data = respon.dataRespon
				if (data.success) {
					$(".modal").modal("hide")

					toastr.success(
						data.message,
						'',
						{
							timeOut: 500,
							fadeOut: 500,
							onHidden: function () {
								window.location.reload()
							}
						}
					)
				}
				else {
					toastr.error(data.message)
				}
			}
		})
	}

</script>

KALBE/Views/Customer/Delete.cshtml
@using kalbe.datamodels
@model Customer
@{
    ViewData["Title"] = "DELETE CUSTOMER";
}

<div class="card">
    <div class="card-body">

        <form asp-action="SureDelete">
            <input type="hidden" name="Id" value="@Model.IntCustomerId" />
            <h3>Are you sure for delete @Model.TxtCustomerName?</h3>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary btn-rounded">Delete</button>
                <a asp-action="Index" class="btn btn-outline-secondary btn-rounded">Back to List</a>
            </div>
        </form>

    </div>
</div>

KALBE/Views/Customer/Detail.cshtml
@using kalbe.datamodels
@model Customer
@{

	ViewData["Title"] = "Detail Customer";
}

<div class="card">
	<div class="card-body">
		<div class="card-title">@ViewData["Title"]</div>
			<div class="mb-4 row">
				<label for="TxtCustomerName" class="col-sm-6 col-form-label">Customer Name</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" id="TxtCustomerName" name="TxtCustomerName" value="@Model.TxtCustomerName" readonly>
					<span id="validateCustomerName" class="text-danger"></span>
				</div>
			</div>
			<div class="mb-4 row">
				<label for="TxtCustomerAddress" class="col-sm-6 col-form-label">Customer Address</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" id="TxtCustomerAddress" name="TxtCustomerAddress" value="@Model.TxtCustomerAddress" readonly>
				</div>
			</div>
			<div class="mb-4 row">
				<label for="Gender" class="col-sm-6 col-form-label">Gender</label>
				<div class="col-sm-6">
					@if (@Model.BitGender == true)
					{
						<input type="text" class="form-control" value="Male" readonly>
					}
					else
					{
						<input type="text" class="form-control" value="Female" readonly>						
					}
				</div>
			</div>
			<div class="mb-4 row">
				<label for="DtmBirthDate" class="col-sm-6 col-form-label">Birth Date</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" id="DtmBirthDate" name="DtmBirthDate" value="@Model.DtmBirthDate.ToString("dd MMMM yyyy")" readonly>
				</div>
			</div>
	</div>
</div>

KALBE/Views/Customer/Edit.cshtml
@using kalbe.datamodels
@model Customer
@{

	ViewData["Title"] = "Edit Customer";
}

<div class="card">
	<div class="card-body">
		<div class="card-title">@ViewData["Title"]</div>
		<form asp-action="Edit" method="post" id="form_input">
			<input type="hidden" id="IntCustomerId" name="IntCustomerId" value="@Model.IntCustomerId" />
			<div class="mb-4 row">
				<label for="TxtCustomerName" class="col-sm-4 col-form-label">Customer Name</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" id="TxtCustomerName" name="TxtCustomerName" value="@Model.TxtCustomerName">
					<span id="validateCustomerName" class="text-danger"></span>
				</div>
			</div>
			<div class="mb-4 row">
				<label for="TxtCustomerAddress" class="col-sm-4 col-form-label">Customer Address</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" id="TxtCustomerAddress" name="TxtCustomerAddress" value="@Model.TxtCustomerAddress">
				</div>
			</div>
			<div class="mb-4 row">
				<label for="BitGender" class="col-sm-4 col-form-label">Gender</label>
				<div class="col-sm-8">
					<select id="BitGender" name="BitGender" class="form-control">
						@if(@Model.BitGender == true)
						{
							<option value="">-- Choose Gender --</option>
							<option value="true" selected>Male</option>
							<option value="false">Female</option>
						}
						else
						{
							<option value="">-- Choose Gender --</option>
							<option value="true">Male</option>
							<option value="false" selected>Female</option>
						}
					</select>
				</div>
			</div>
			<div class="mb-4 row">
				<label for="DtmBirthDate" class="col-sm-4 col-form-label">Birth Date</label>
				<div class="col-sm-8">
					@Html.TextBoxFor(
					model => model.DtmBirthDate ,
					"{0:yyyy-MM-dd}",
					new {
					@type= "date",
					@class = "form-control",
					@value = Model.DtmBirthDate
					}
					)
				</div>
			</div>

			<div class="modal-footer">
				<div class="col-sm-12">
					<a class="btn btn-outline-secondary btn-rounded" asp-controller="Customer" asp-action="Index">Back to List</a>
					<button type="submit" style="float:right" class="btn btn-primary btn-rounded">Submit</button>
				</div>
			</div>
		</form>

	</div>
</div>

<script>



	$("#form_input").validate({
		errorClass: "text-danger",
		rules: {
			TxtCustomerName: {
				required: true,
				minlength: 3,
			},
			TxtCustomerAddress: "required",
			BitGender: "required",
			DtmBirthDate: "required"
		},
		messages: {
			TxtProductName: {
				required: "Please fill name customer!",
				minlength: "The Name must consist of at least 3 character!",
			},
			TxtCustomerAddress: "Please fill name customer!",
			BitGender: "Choose your gender",
			DtmBirthDate: "Please fill your birth date"
		},
		submitHandler: function (form) {
			var dataForm = $(form).serialize();
			var CustomerName = $("#TxtCustomerName").val();

			$.ajax({
				url: "/Customer/CheckNameIsExist",
				//method: "GET"
				type: "GET",
				data: { CustomerName: CustomerName },
				dataType: "json",
				success: function (respon) {
					if (respon) {
						$("#validateCustomerName").text("Name Customer is already exist")
						return true
					}
					else {
						fungsiSubmit(dataForm)
					}
				}
			})
		}
	})

	function fungsiSubmit(dataParam) {
		$.ajax({
			url: "/Customer/Edit",
			type: "POST",
			dataType: "json",
			data: dataParam,
			success: function (respon) {
				var data = respon.dataRespon
				if (data.success) {
					$(".modal").modal("hide")

					toastr.success(
						data.message,
						'',
						{
							timeOut: 500,
							fadeOut: 500,
							onHidden: function () {
								window.location.reload()
							}
						}
					)
				}
				else {
					toastr.error(data.message)
				}
			}
		})
	}

</script>

KALBE/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">WELCOME</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

KALBE/Views/Product/Create.cshtml
@using kalbe.datamodels
@model Produk
@{

	ViewData["Title"] = "Create Product";
}

<div class="card">
	<div class="card-body">
		<div class="card-title">@ViewData["Title"]</div>
		<form asp-action="Create" method="post" id="form_input">
			<div class="mb-4 row">
				<label for="TxtProductName" class="col-sm-4 col-form-label">Product Name</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" id="TxtProductName" name="TxtProductName" value="@Model.TxtProductName">
					<span id="validateProductName" class="text-danger"></span>
				</div>
			</div>
			<div class="mb-4 row">
				<label for="IntQty" class="col-sm-4 col-form-label">Quantity</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" id="IntQty" name="IntQty" value="@Model.IntQty">
				</div>
			</div>
			<div class="mb-4 row">
				<label for="DecPrice" class="col-sm-4 col-form-label">Price</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" id="DecPrice" name="DecPrice" value="@Model.DecPrice">
				</div>
			</div>

			<div class="modal-footer">
				<div class="col-sm-12">
					<a class="btn btn-outline-secondary btn-rounded" asp-controller="Product" asp-action="Index">Back to List</a>
					<button type="submit" style="float:right" class="btn btn-primary btn-rounded">Submit</button>
				</div>
			</div>
		</form>

	</div>
</div>

<script>



	$("#form_input").validate({
		errorClass: "text-danger",
		rules: {
			TxtProductName: {
				required: true,
				minlength: 3,
			},
			IntQty: {
				required: true,
				number: true,
				min:0
			},
			DecPrice: {
				required: true,
				number: true,
			}
		},
		messages: {
			TxtProductName: {
				required: "Please fill name product!",
				minlength: "The Name must consist of at least 3 character!",
			},
			IntQty: {
				required: "Please fill Quantity",
				number: "Please fill number only",
				min: "gaboleh < 0",
			},
			DecPrice: {
				required: "Please fill Quantity",
				number: "Please fill number only",
			}
		},
		submitHandler: function (form) {
			var dataForm = $(form).serialize();
			var ProductName = $("#TxtProductName").val();

			$.ajax({
				url: "/Product/CheckNameIsExist",
				//method: "GET"
				type: "GET",
				data: { ProductName: ProductName },
				dataType: "json",
				success: function (respon) {
					if (respon) {
						$("#validateProductName").text("Name Product is already exist")
						return true
					}
					else {
						fungsiSubmit(dataForm)
					}
				}
			})
		}
	})

	function fungsiSubmit(dataParam) {
		$.ajax({
			url: "/Product/Create",
			type: "POST",
			dataType: "json",
			data: dataParam,
			success: function (respon) {
				var data = respon.dataRespon
				if (data.success) {
					$(".modal").modal("hide")

					toastr.success(
						data.message,
						'',
						{
							timeOut: 500,
							fadeOut: 500,
							onHidden: function () {
								window.location.reload()
							}
						}
					)
				}
				else {
					toastr.error(data.message)
				}
			}
		})
	}

</script>

KALBE/Views/Product/Delete.cshtml
@using kalbe.datamodels
@model Produk
@{
    ViewData["Title"] = "DELETE PRODUCT";
}

<div class="card">
    <div class="card-body">

        <form asp-action="SureDelete">
            <input type="hidden" name="Id" value="@Model.IntProductId" />
            <h3>Are you sure for delete @Model.TxtProductName?</h3>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary btn-rounded">Delete</button>
                <a asp-action="Index" class="btn btn-outline-secondary btn-rounded">Back to List</a>
            </div>
        </form>

    </div>
</div>

KALBE/Views/Product/Detail.cshtml
@using kalbe.datamodels
@model Produk
@{

	ViewData["Title"] = "Detail Product";
}

<div class="card">
	<div class="card-body">
		<div class="card-title">@ViewData["Title"]</div>
		<div class="mb-4 row">
			<label for="DtInserted" class="col-sm-6 col-form-label">Create Date</label>
			<div class="col-sm-6">
				<input type="text" class="form-control" id="DtInserted" name="DtInserted" value="@Model.DtInserted" readonly>
			</div>
		</div>
		<div class="mb-4 row">
			<label for="TxtProductCode" class="col-sm-6 col-form-label">Product Code</label>
			<div class="col-sm-6">
				<input type="text" class="form-control" id="TxtProductCode" name="TxtProductCode" value="@Model.TxtProductCode" readonly>
			</div>
		</div>
		<div class="mb-4 row">
			<label for="TxtProductName" class="col-sm-6 col-form-label">Product Name</label>
			<div class="col-sm-6">
				<input type="text" class="form-control" id="TxtProductName" name="TxtProductName" value="@Model.TxtProductName" readonly>
			</div>
		</div>
		<div class="mb-4 row">
			<label for="IntQty" class="col-sm-6 col-form-label">Quantity</label>
			<div class="col-sm-6">
				<input type="text" class="form-control" id="IntQty" name="IntQty" value="@Model.IntQty" readonly>
			</div>
		</div>
		<div class="mb-4 row">
			<label for="DecPrice" class="col-sm-6 col-form-label">Price</label>
			<div class="col-sm-6">
				<input type="text" class="form-control" id="DecPrice" name="DecPrice" value="@Model.DecPrice" readonly>
			</div>
		</div>
	</div>
</div>

KALBE/Views/Product/Edit.cshtml
@using kalbe.datamodels
@model Produk
@{

	ViewData["Title"] = "Edit Product";
}

<div class="card">
	<div class="card-body">
		<div class="card-title">@ViewData["Title"]</div>
		<form asp-action="Edit" method="post" id="form_input">
			<input type="hidden" id="IntProductId" name="IntProductId" value="@Model.IntProductId" />
			<div class="mb-4 row">
				<label for="TxtProductCode" class="col-sm-4 col-form-label">Product Code</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" placeholder="[@Model.TxtProductCode]" readonly>
				</div>
			</div>
			<div class="mb-4 row">
				<label for="TxtProductName" class="col-sm-4 col-form-label">Product Name</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" id="TxtProductName" name="TxtProductName" value="@Model.TxtProductName">
					<span id="validateProductName" class="text-danger"></span>
				</div>
			</div>
			<div class="mb-4 row">
				<label for="IntQty" class="col-sm-4 col-form-label">Quantity</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" id="IntQty" name="IntQty" value="@Model.IntQty">
				</div>
			</div>
			<div class="mb-4 row">
				<label for="DecPrice" class="col-sm-4 col-form-label">Price</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" id="DecPrice" name="DecPrice" value="@Model.DecPrice">
				</div>
			</div>

			<div class="modal-footer">
				<div class="col-sm-12">
					<a class="btn btn-outline-secondary btn-rounded" asp-controller="Product" asp-action="Index">Back to List</a>
					<button type="submit" style="float:right" class="btn btn-primary btn-rounded">Submit</button>
				</div>
			</div>
		</form>

	</div>
</div>

<script>



	$("#form_input").validate({
		errorClass: "text-danger",
		rules: {
			TxtProductName: {
				required: true,
				minlength: 3,
			},
			IntQty: {
				required: true,
				number: true,
			},
			DecPrice: {
				required: true,
				number: true,
			}
		},
		messages: {
			TxtProductName: {
				required: "Please fill name product!",
				minlength: "The Name must consist of at least 3 character!",
			},
			IntQty: {
				required: "Please fill Quantity",
				number: "Please fill number only",
			},
			DecPrice: {
				required: "Please fill Price",
				number: "Please fill number only",
			}
		},
		submitHandler: function (form) {
			var dataForm = $(form).serialize();
			$.ajax({
				url: "/Product/Edit",
				type: "POST",
				dataType: "json",
				data: dataForm,
				success: function (respon) {
					var data = respon.dataRespon
					if (data.success) {
						$(".modal").modal("hide")
						toastr.success(
							data.message,
							'',
							{
								timeOut: 500,
								fadeOut: 500,
								onHidden: function () {
									window.location.reload()
								}
							}
						)
					}
					else {
						toastr.error(data.message)
					}
				}
			})
		}
	})

	function fungsiSubmit(dataParam) {
		$.ajax({
			url: "/Product/Edit",
			type: "POST",
			dataType: "json",
			data: dataParam,
			success: function (respon) {
				var data = respon.dataRespon
				if (data.success) {
					$(".modal").modal("hide")

					toastr.success(
						data.message,
						'',
						{
							timeOut: 500,
							fadeOut: 500,
							onHidden: function () {
								window.location.reload()
							}
						}
					)
				}
				else {
					toastr.error(data.message)
				}
			}
		})
	}

</script>

KALBE/Views/Shared/_Sidebar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!-- ============================================================== -->
<!-- Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->
<aside class="left-sidebar" data-sidebarbg="skin6">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar" data-sidebarbg="skin6">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" href="index.html"
                       aria-expanded="false">
                        <i data-feather="home" class="feather-icon"></i><span class="hide-menu">Dashboard</span>
                    </a>
                </li>
                <li class="list-divider"></li>
                <li class="nav-small-cap"><span class="hide-menu">Master</span></li>

                <li class="sidebar-item">
                    <a class="sidebar-link" asp-controller="Product" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="users" class="feather-icon"></i><span class="hide-menu">
                            Product
                        </span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" asp-controller="Customer" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="users" class="feather-icon"></i><span class="hide-menu">
                            Customer
                        </span>
                    </a>
                </li>            


                <li class="list-divider"></li>
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" href="authentication-login1.html"
                       aria-expanded="false">
                        <i data-feather="log-out" class="feather-icon"></i><span class="hide-menu">Logout</span>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>
<!-- ============================================================== -->
<!-- End Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->